------
title: "Small Errors, Big Consequences: Lessons from Data Mismanagement in Business"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```
#Introduction

In today’s data-driven world, even a small data error can lead to serious consequences. This paper explores the concept of “Small Errors, Big Consequences” through real-world examples, including a personal case involving cancer detection and treatment technology.

Case Study: Cancer Cell Detection Program
Some times ago I tried to write a program which is related to the detection and prediction of breast cancer cells. 
The program worked in a way that could recognized cancer cells from healthy cells (malignant cells and benign cells) based on color or black-and-white imaging (color spectrum) of the breast and was designed to locate the origin.
The program was connecting to a robot, which would identify the coordinates of cancer cells using 3D imaging and then begin laser therapy.

Why use a robot?
To minimize human error. This method is typically effective for eliminating very small, early-stage tumors (Laser Ablation).
The robot was supposed to irradiate the area around each malignant cell with a margin of error between 1 to 7 nanometers.
However, the programming encountered some flaws and failed to accurately identify malignant cells based on color spectrum analysis. As a result, instead of targeting the cancerous cells, the laser mistakenly hit surrounding healthy cells, causing unintended burns.
This was a small but clear example of "Small Errors, Big Consequences."



